### ISSUE TITLE
Important: Div wrappers

### ISSUE THREAD

**Issue by blerude** [Kerrie-jr/prj-rev-bwfs-dasmoto#1]
https://github.com/Kerrie-jr/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L12-L15

You should use divs to wrap groups of related elements so that you can indicate their relation and style them more easily as a group vs. needing to do so individually.

**Comment by Kerrie-jr** [comment]
Thanks - done!  Thanks for the review, it's very helpful.
