### ISSUE TITLE
Subtle: CSS formatting

### ISSUE THREAD

**Issue by blerude** [Kerrie-jr/prj-rev-bwfs-dasmoto#3]
https://github.com/Kerrie-jr/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/Resources/CSS/style.css#L1-L6

You've formatted your selectors in two different ways here. It's best to pick one and stick with it. Also, the typical way of formatting CSS to make it as readable as possible is like this: 

```
h1 {
      font-size: 100px; 
      color: khaki; 
      font-weight: bold; 
      text-align: center;
} 
```

**Comment by Kerrie-jr** [comment]
Thanks - I've corrected those and will use the style code you've shown.
