### ISSUE TITLE
Subtle: Class vs. id

### ISSUE THREAD

**Issue by blerude** [Kerrie-jr/prj-rev-bwfs-dasmoto#4]
https://github.com/Kerrie-jr/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L12

Because the class here is applied only once, you can make it an id. Ids are used for unique elements only as a way to indicate their one-of-a-kind character.

**Comment by Kerrie-jr** [comment]
Thanks - I was hesitant to use the id - it seems we've been getting steered clear of using ids unless there was a good reason.  I've updated the project.
