### ISSUE TITLE
Great! Global styling

### ISSUE THREAD

**Issue by blerude** [Kerrie-jr/prj-rev-bwfs-dasmoto#5]
https://github.com/Kerrie-jr/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/Resources/CSS/style.css#L1

I like how you used the body tag to apply the styling here to the whole document instead of having to write it multiple times.

**Comment by Kerrie-jr** [comment]
thanks - it seemed the way to go given that a single font was used throughout.
