### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [Kerrie-jr/prj-rev-bwfs-dasmoto#6]
Grade: Meets Expectations

Great job on this project! You've included all the necessary elements and you're definitely developing as an HTML/CSS programmer. 

Moving forward, focus on consistency. On multiple occasions, you'd format things one way one time, and a different way the next (CSS format, styling application). While programming offers you the freedom to do things in the way that makes sense to you, you have to be consistent in the choices you make. You should also get used to using div wrappers as a way to group and distinguish elements. Finally, adding comments to your code to explain their purpose and role within the project is a great habit to develop. Again, good job here and congratulations on your first project!

**Comment by Kerrie-jr** [comment]
Thank you. I assume that I should respond to each of these and close them?
